### ISSUE TITLE
README Missing 

### ISSUE THREAD

**Issue by seanlowjk** [tanamaroby/tesseract_ocr#1]
README File is missing from the repository. 

it is important for passerbys to know what this repository is about. 😕

**Comment by tanamaroby** [comment]
# Bruh moment

## Issue
- Lack of `README.md`
- Bruh moment

## Developer response
- `README.md` can be found in other repository

Thank you for contributing to my repository 👍

**Comment by seanlowjk** [comment]
Closed due to epic comment
